#spring:
#  application:
#    name: YKR-eureka
#  zipkin:
#    base-url: http://localhost:9411
#  boot:
#    admin:
#      client:
#        url: http://localhost:8084
#
#
#server:
#  port: 8761
#
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#      #include: ["health","info"]  #信息监控和健康检查.如果此处是用的*则表示所有的服务都需要健康检查
#      include: health,info
#
#eureka:
#  instance:
#    hostname: localhost
#  client:   #表示是否将自己注册到eureka,因为要构建集群环境，需要将自己注册到集群，所以应该要开启
#    register-with-eureka: true
#    #表示是否从eureka获取注册的信息，如果是单一节点，不需要同步其他eureka节点，则可以设置为false,但此处为集群，应该设置为true
#    fetch-registry: true
#    serviceUrl:
#      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    defaultZone: http://ip:${server.port}/eureka/,http://ip:${server.port}/eureka,http://ip:${server.port}/eureka/
#    #eureka的集群就是多个eureka之间互相注册，一个eureka注册一个eureka而来
spring:
  application:
    name: YKR-eureka
  zipkin:
    #base-url: http://192.168.154.128:9411
  base-url: http://localhost:9411
  boot:
    admin:
      client:
        #url: http://192.168.154.128:8084
      url: http://localhost:8084


server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
      #include: ["health","info"]  #信息监控和健康检查.如果此处是用的*则表示所有的服务都需要健康检查
      include: health,info

eureka:
  instance:
    hostname: localhost
  client:   #表示是否将自己注册到eureka,因为要构建集群环境，需要将自己注册到集群，所以应该要开启
    register-with-eureka: true
    #表示是否从eureka获取注册的信息，如果是单一节点，不需要同步其他eureka节点，则可以设置为false,但此处为集群，应该设置为true
    fetch-registry: true
    serviceUrl:
    #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    defaultZone: http://ip:${server.port}/eureka/,http://ip:${server.port}/eureka,http://ip:${server.port}/eureka/
    #eureka的集群就是多个eureka之间互相注册，一个eureka注册一个eureka而来