spring:
  application:
    name: YKR-zuul
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #表示向服务注册中心注册服务



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
      #include: ["health","info"]  #信息监控和健康检查.如果此处是用的*则表示所有的服务都需要健康检查
      include: health,info





#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: hello-spring-cloud-web-admin-ribbon
#    api-b:
#      path: /api/b/**
#      serviceId: hello-spring-cloud-web-admin-feign  #表示网关要聚合两个服务，一个是ribbon，另一个是feign