spring:
  application:
    name: YKR-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411  #9411是zipkin的默认端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false




#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#      #include: ["health","info"]  #信息监控和健康检查.如果此处是用的*则表示所有的服务都需要健康检查
#      include: health,info