spring:
  application:
    name: YKR-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

#    datasource:
#      url: jdbc:mysql://localhost:3306/kr?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/kr?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000 				# 等待连接获取的最大超时时间
  #集中解决各种编码问题
  banner:
    charset: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  #     spring mvc 视图解析器
  mvc:
    view:
      prefix: /
      suffix: .html
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区设置
    time-zone: GMT+8






server:
  port: 8501

mybatis:
  type-aliases-package: com.YKR.service.admin.domain
  mapper-locations: classpath*:com.YKR.service.admin.mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

