spring:
  application:
    name: YKR-service-sso
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/kr?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000 				# 等待连接获取的最大超时时间
server:
  port: 8503
# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.YKR.common.domain
  mapper-locations: classpath*:com.YKR.service.sso.mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

