spring:
  application:
    name: YKR-service-sso
  zipkin:
    base-url: http://192.168.154.128:9411
  boot:
    admin:
      client:
        url: http://192.168.154.128:8084
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库url
    url: jdbc:mysql://localhost:3306/kr?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # 数据库访问账户
    username: root
    # 数据库访问密码
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                # 最大的连接数
      max-wait-millis: 60000 				# 等待连接获取的最大超时时间

  thymeleaf:                   #thymeleaf的配置
    cache: false               #开发时关闭缓存，不然没发看到实时页面
    mode: LEGACYHTML5          #用非严格的HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 8503
# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: com.YKR.common.domain
  mapper-locations: classpath*:com.YKR.service.sso.mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.154.128:8761/eureka/,http://192.168.154.128:8861/eureka,http://192.168.154.128:8961/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

