spring:
  application:
    name: YKR-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411  #9411是zipkin的默认端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false


  endpoints:
    web:
      exposure:
        include: "*"
