spring:
  application:
    name: YKR-admin
  zipkin:   #加入zipkin链路追踪
    base-url: http://localhost:9411


server:
  port: 8084

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        #include: ["health","info"]  #信息监控和健康检查.如果此处是用的*则表示所有的服务都需要健康检查
#      include: health,info

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/